# Generated by Django 4.1.3 on 2022-11-10 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_recipe_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficult', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.difficult'),
        ),
    ]
